### PR TITLE
DB and PHP files for the android app

### PR DESCRIPTION
**Pull request by Sumudu-Sahan**
https://drive.google.com/file/d/0B_WrcBIXQ8igU3E3VlllZnVGX00/view?usp=sharing

### CODE REVIEW

**Comment by gayanhewa** [comment]
@Sumudu-Sahan without doing this, @danishka or someone with merge access to the dev repo can rebase it against the master. Instead of adding a merge commit.

**Review by gayanhewa — CHANGES_REQUESTED** [review]
I think this wouldn't be needed if we move to a Github flow, if not we can rebase dev against master to keep to up to date

**Comment by Sumudu-Sahan** [comment]
guys, here is the android project. please debug this. 

https://drive.google.com/file/d/0B_WrcBIXQ8igLTNvRDlPY2NzVGc/view?usp=sharing

**Comment by Sumudu-Sahan** [comment]
guys, here is the android project. please debug this. 

and add the URL when the admin sent.

https://drive.google.com/file/d/0B_WrcBIXQ8igLTNvRDlPY2NzVGc/view?usp=sharing

**Pull request closed without merging**
