### PR TITLE
Compiling Assets (Laravel Mix)

### PR DESCRIPTION
**Pull request by thilinag**
# What you've done
Removed following links 
```
    <!-- Loading Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Abhaya+Libre" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="/public/css/flat-ui.min.css" rel="stylesheet">
```
Added 

`<link href="{{ asset('css/app.css') }}" rel="stylesheet">`

Have to run npm run dev to build app.css and app.js (app.js is not added to the project yet).

# Why have you done it

Using Laravel Mix to build the css assets.

https://github.com/reliefsupports/reliefsupports.org/issues/121

### CODE REVIEW

**Comment by gayanhewa** [comment]
@thilinag what extra steps should we take when introducing new css or updating existing css files?

**Comment by thilinag** [comment]
@gayanhewa 
Can add/import stuff to /resources/assets/sass/app.scss.
And then have to npm run dev or npm run production to build the app.css. 

Only difference of dev vs production is production will be minified. 
https://laravel.com/docs/5.4/mix

**Comment by gayanhewa** [comment]
You will have to edit the base and change it to dev for this PR. Apart from that looks alright to me.

**Comment by thilinag** [comment]
Added responsive styles for mobiles for tables in homepage and detail pages.

screenshot_2017-05-31_10-55-18

**Comment by thilinag** [comment]
added abhaya libre 700 to app.scss ref: https://github.com/reliefsupports/reliefsupports.org/pull/143

**Comment by kasunben** [comment]
@thilinag machan, if you got some time can you fix the conflicts and test the app locally, to make sure nothing is broken. Bit afraid to merge PRs without testing in locally since the last night incident :D

**Comment by kasunben** [comment]
@thilinag and there are some path issue in the server.. still couldn;t able attend to fix it. So, still we can't use `asset()` method even we set the `APP_URL` in remote server. Will fix it, but meanwhile can we keep paths in `master.blade.php` as `/public/css/...` for now.

**Comment by thilinag** [comment]
@thinkholic Looks like there's a mismatch in server setup and repo. 
Its mentioned at https://github.com/reliefsupports/reliefsupports.org/issues/65 also. 

In local if i put /public/css/... it doesn't work for me. /css/... works.

**Comment by kasunben** [comment]
yes yes, same for me. It's not working locally with `/public`. NVM. We can temporally handle that when we deploying. Let's keep it as it is. :)

**Comment by thilinag** [comment]
@thinkholic shall i push with /public or without ?

**Comment by kasunben** [comment]
No no keep it. I'll change when merging.

**Comment by kasunben** [comment]
btw, you tested the app in local? everything seems okay.. right? :)

**Comment by thilinag** [comment]
yes LGTM

**Comment by kasunben** [comment]
Perfect. :)

**Comment by kasunben** [comment]
@thilinag took it. btw, there is a small bug as I noticed. menu is not displaying (toggle button isn't working) in mobile view. Let's fix it later.

**Comment by kasunben** [comment]
My bad. it's working. 👍

**Comment by thilinag** [comment]
Need to fix the asset path issue though

**Pull request merged**
