### PR TITLE
Cleaned master layout file, added css/js into mix. 

### PR DESCRIPTION
**Pull request by Chathula**
# What you've done
Cleaned the Master file with the usage of laravel mix. now we can us `resources/assets/js/app.js` and `resources/assets/js/app.scss` for js and css codes. 

# Why have you done it
it is better to use laravel mix for laravel. it can minify code in production and can bundle everything well.
also now we can use sass(scss) if we want.

### CODE REVIEW

**Comment by Chathula** [comment]
Ok i wil put some screenshots!

**Comment by Chathula** [comment]
There is another PR https://github.com/reliefsupports/reliefsupports.org/pull/122

Check one of these and clean unwantd PRs!!

**Comment by gayanhewa** [comment]
@Chathula yes. Not all changes are identical. It would be great if you coordinate efforts with @thilinag

**Comment by Chathula** [comment]
But i think this is a must! This is the laravel recommended way to handle assets!

**Comment by Chathula** [comment]
Will see!! :D

**Comment by kasunben** [comment]
Will need to fix the conflicts @Chathula

**Comment by Chathula** [comment]
now everything is good!!

**Comment by kasunben** [comment]
@thilinag anything to add or good to go?

**Comment by thilinag** [comment]
@thinkholic good to go. LGTM. When we are going live need to run `npm run prod` to generate assets production build .

@Chathula there's one more conflict in resources/views/layouts/master.blade.php

**Comment by kasunben** [comment]
@Chathula Can you fix the conflict here, so we can merge this.

**Comment by Chathula** [comment]
@thilinag @thinkholic fixed the conflicts.. now we can merge this!!

**Comment by kasunben** [comment]
@Chathula perfect. Will do. 

@naveendw

**Comment by kasunben** [comment]
Got some errors with running  `npm run dev` so did some changes on `package.json`.

Merging this.

**Pull request merged**
