### PR TITLE
fixed assets path issue

### PR DESCRIPTION
**Pull request by Chathula**

### CODE REVIEW

**Review by Shashika — APPROVED** [review]

**Comment by gayanhewa** [comment]
@Chathula can you change the base to dev? We can get @danishka to merge this in since its ready

**Comment by thilinag** [comment]
@gayanhewa we should use app.css without adding css separately for fonts, bootstrap, theme etc.

**Review by gayanhewa — APPROVED** [review]

**Comment by Chathula** [comment]
yep, laravel mix usage is the best way for work!

**Review by isuru4lk — APPROVED** [review]

**Comment by chamilad** [comment]
So should this PR be closed and reopened against `dev`?

**Comment by kasunben** [comment]
@chamilad No need to close. I change the base to 'dev' now once we tested this on local, we can merge. @gayanhewa @Chathula

**Comment by kasunben** [comment]
Plus, I think we have to change the `APP_URL` in `.env` file  accordingly to work this.. right?

**Pull request merged**
